city_list = ["Tokyo", "Mexico City", "Mumba", "New York", "Sao Paulo", "Delhi", "Calcutta", "Jakarta", "Buenos Aires",
             "Dhaka", "Shanghai", "Los Angeles", "Karachi", "Lagos",
             "Rio de Janeiro", "Osaka", "Cairo", "Beijing", "Moscow", "Metro Manila", "Istanbul", "Paris", "Seoul",
             "Tianjin", "Chicago", "Lima", "Bogota", "London", "Tehran",
             "Hong Kong", "Chennai", "Bangalore", "Bangkok", "Dortmund", "Lahore", "Hyderabad", "Wuhan", "Baghdad",
             "Kinshasa", "Riyadh", "Santiago", "Miami", "Belo Horizonte",
             "Philadelphia", "St Petersburg", "Ahmadabad", "Madrid", "Toronto", "Ho Chi Minh City", "Chongqing",
             "Shenyang", "Dallas", "Pune", "Khartoum", "Singapore", "Atlanta",
             "Sydney", "Barcelona", "Houston	", "Chittagong", "Boston	", "Washington ", "Hanoi", "Yangon",
             "Bandung", "Detroit	", "Jidda", "Milan", "Guadalajara", "Surat", "Guangzhou",
             "Porto Alegre", "Casablanca", "Alexandria", "Frankfurt", "Melbourne", "Ankara", "Abidjan Cote d", "Recife",
             "Monterrey", "Montréal", "Chengdu", "Phoenix", "Pusan", "Brasilia",
             "Johannesburg", "Kabul", "Salvador", "Algiers", "San Francisco", "Düsseldorf", "Fortaleza", "Medellin",
             "Berlin", "Pyongyang", "Caracas", "Xian", "Athens", "Cape Town",
             "Changchun", "Kanpur", "Cologne Bonn", "Tel Aviv-Jaffa", "Seattle", "Addis Ababa", "Curitiba", "Nairobi",
             "Kano", "Luanda", "Jaipur", "Harbin", "Naples", "Katowice",
             "San Diego", "Fukuoka, Kitakyushu", "Nanjing", "Dar es Salaam", "Zibo", "Surabaja", "Dalian", "Campinas",
             "Durban", "Stuttgart", "Hamburg", "Incheon", "Cali", "Jinan",
             "Lucknow", "Kiev", "Faisalabad", "Rome", "Aleppo", "Izmir", "Minneapolis, St. Paul", "Taiyuan", "Taegu",
             "Guiyang", "Taipei", "Guayaquil", "Qingdao", "Valencia", "Nagpur",
             "Ibadan", "San Juan", "Dakar", "Damascus", "Munich", "Zhengzhou", "Denver-Aurora", "Tampa",
             "St. Petersburg", "Maracaibo", "Zaozhuang", "Birmingham", "Warsaw", "Baltimore",
             "Vienna", "Havana", "Manchester", "Belem", "Mashhad", "Port-au-Prince", "Tashkent", "Vancouver", "Patna",
             "Medan", "Handan", "Tripoli", "St. Louis", "Liupanshui", "Toluca",
             "Changsha", "Tunis", "Douala", "Linyi", "Liuan", "Accra", "Indore", "Wanxian", "Hangzhou", "Lisbon",
             "Tianmen", "Barranquilla", "Santo Domingo", "Beirut", "Goiania", "Rabat",
             "Heze", "Jinxi", "Antananarivo", "Puebla", "Rawalpindi", "Sapporo", "Portland", "Hai Phong", "Cleveland",
             "Baku", "Asuncion", "Las Vegas", "Kyoto"]
